### ISSUE TITLE
Post type controls

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/ubiquitousblocks#1]
Can we change these to checkbox controls? It's kinda hard to select more than one and it doesn't look that clean right now. I think checkboxes would be better.

<img width="265" alt="Screen Shot 2020-01-21 at 5 34 49 AM" src="https://user-images.githubusercontent.com/158918/72801801-f02edb00-3c0f-11ea-9bf4-30187e6063f6.png">

**Comment by seb86** [comment]
Not sure if multiple checkboxes are supported yet. Going to need to request more documentation for the CheckboxControl.

**Comment by nickhamze** [comment]
I assume it is from this:
https://github.com/WordPress/gutenberg/tree/master/packages/components/src/checkbox-control

**Comment by seb86** [comment]
Yes. I have posted an issue about it. https://github.com/WordPress/gutenberg/issues/19792

**Comment by nickhamze** [comment]
I feel a bit helpless, I wish I could help with this. All I can do it some power searching. I found a few links that talk about this. Maybe they will help:
https://stackoverflow.com/questions/55653897/in-a-wordpress-gutenberg-block-how-can-i-create-a-multiple-checkboxes-using-a-ch
https://wordpress.stackexchange.com/questions/338423/multiple-checkboxes-gutenberg-control

**Comment by seb86** [comment]
react-select works. Saves the meta differently but the query to find reusable block posts still returns the results the same.
