### ISSUE TITLE
Doesn't work when "bottom" is selected.

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/ubiquitousblocks#2]
When a select the top option it works great but when I select the bottom one nothing happens. 

<img width="290" alt="Screen Shot 2020-01-21 at 5 37 05 AM" src="https://user-images.githubusercontent.com/158918/72801902-2a987800-3c10-11ea-9d50-699c75616c27.png">

I think we should also change the labels to be:
Before all content.
After all content.

**Comment by seb86** [comment]
Tweaked labels and fixed query so blocks show after all content too.
