### ISSUE TITLE
Make sure all dependencies are up to date

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/ubiquitousblocks#3]
GitHub says one of the dependencies is vulnerable can we make sure they are all up to date.

**Comment by seb86** [comment]
Which one?

**Comment by nickhamze** [comment]
https://github.com/sortabrilliant/ubiquitousblocks/network/alerts

**Comment by seb86** [comment]
I will see if I can override it. A lot of the packages are handled via this script. https://github.com/ahmadawais/create-guten-block

**Comment by nickhamze** [comment]
I don't know what the differences are or anything but JR is porting all my old blocks over to something called WP Scripts instead of CGB:
https://github.com/sortabrilliant/ghostwriter/commit/4ac97ac9ead77321641f40de1988defd1b60871f
https://developer.wordpress.org/block-editor/packages/packages-scripts/

**Comment by seb86** [comment]
Cool. I will look into porting over once I have made the requested tweaks and tested more.

**Comment by nickhamze** [comment]
Sounds good. I'm so excited. I can't wait to see how people react.

**Comment by nickhamze** [comment]
I found out about this today too. Suppose to make creating blocks really easy:
https://github.com/WordPress/gutenberg/pull/19773
