### ISSUE TITLE
Copy Updates

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/ubiquitousblocks#4]
I want to update some of the copy.

Where it says "Select the post types this reusable block will be shown on."
Could we change it to "What post types should we add your blocks to?"

Where it says "Select where you want the reusable block to display of every post type you selected."
Could we change it to "Where do you want your blocks?"

Where it says "Enter the number you wish this reusable block to show in order of."
Could we change it to "Which order should be put them in?"

In the plugin description where it says "Reusable Blocks are accessible via the WordPress Dashboard. The reusable blocks can also be set to stick at the top or bottom of specific post types in any order."
Could we change it to "Display reusable blocks everywhere. With Ubiquitous Blocks you can add reusable blocks to every page/post with a few clicks of the mouse."

**Comment by seb86** [comment]
Done
