### ISSUE TITLE
ISBAT: Display server-side rendered blocks

### ISSUE THREAD

**Issue by seb86** [sortabrilliant/ubiquitousblocks#5]
I installed the plugin on one of my sites today and noticed that it does not render server-sided blocks. For example, use the [social profile links block from CoBlocks](https://github.com/godaddy-wordpress/coblocks/blob/master/src/blocks/social-profiles/index.php). Nothing for that block shows.

Need to identify the type of block and fetch it's callback.

**Comment by nickhamze** [comment]
@seb86 Is this going to be hard to fix? Not really sure what it all entails.

**Comment by seb86** [comment]
Currently researching.

**Comment by seb86** [comment]
May need to add a block checker. Something like so.

```
if ( has_blocks( $post->post_content ) ) {
    $blocks = parse_blocks( $post->post_content );

    if ( $blocks[0]['blockName'] === 'core/heading' ) {
        // Do something here!
    }
}
```

**Comment by seb86** [comment]
This will re-render the blocks but according to the documentation it says "Parses **dynamic blocks** out of post_content" not server-side blocks.

```php
if ( has_blocks( $post->post_content ) ) {
    $blocks = do_blocks( $post->post_content );
}
```

**Comment by seb86** [comment]
Something like this. WIP

```php
if ( has_blocks( $post->post_content ) ) {
    $blocks = parse_blocks( $post->post_content );

    foreach( $blocks as $block ) {
      // Get block type.
      $block_type = WP_Block_Type_Registry::get_instance()->get_registered( $block['blockName'] );

      if ( ! $block_type->is_dynamic() ) {
        // Render callback here!
      }
    }
}
```

**Comment by nickhamze** [comment]
It's all greek to me, haha. Whatever you think will work let's do it.

**Comment by nickhamze** [comment]
@seb86 Did you find a solution that you think will work?

**Comment by seb86** [comment]
@nickhamze I have not looked today. Been busy catching up with other work. Will run some tests now with what I have found so far.

**Comment by seb86** [comment]
Did some testing and it appears that having a server side rendered block inside another block that is dynamic does not load the block. Otherwise a server side block does show.

Only the inline comment data remains in the DOM where the block is suppose to show. This issues will need more testing to make sure it's not the blocks I am using in particular that have an issue.

Help testing this issue from other block developers would be great.

**Comment by nickhamze** [comment]
Does this fix make the plugin work with more blocks even if it doesn't work with every one? If yes, let's push a small update with this fix and I'll see if I can get some more feedback from other block developers.

**Comment by seb86** [comment]
I'm afraid not. The code snippet above just duplicates the same content.

**Comment by seb86** [comment]
Closing this issue to open a new now we know more about the problem.
