### ISSUE TITLE
Migrate from CGB to @wordpress/scripts

### ISSUE THREAD

**Issue by Mamaduka** [sortabrilliant/ubiquitousblocks#9]
Currently, the plugin uses mix of `CGB` and Grunt for development. The build process also triggers an error and fails Deployment action.

`@wordpress/scripts` is a recommended package for block development and we're using it in all other plugins.

**Comment by Mamaduka** [comment]
@nickhamze can you give this another round of tests, just in case I missed something.

**Comment by nickhamze** [comment]
@Mamaduka Works fine me.

**Comment by Mamaduka** [comment]
The latest release is deployed to WP.org.
